// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package samplemodule.proxies;

public class SubEntity
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject subEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SampleModule.SubEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SubTestText("SubTestText"),
		SubEntity_TestEntityAssocAccount("SampleModule.SubEntity_TestEntityAssocAccount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SubEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SampleModule.SubEntity"));
	}

	protected SubEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject subEntityMendixObject)
	{
		if (subEntityMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SampleModule.SubEntity", subEntityMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SampleModule.SubEntity");

		this.subEntityMendixObject = subEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SubEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static samplemodule.proxies.SubEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return samplemodule.proxies.SubEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static samplemodule.proxies.SubEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new samplemodule.proxies.SubEntity(context, mendixObject);
	}

	public static samplemodule.proxies.SubEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return samplemodule.proxies.SubEntity.initialize(context, mendixObject);
	}

	public static java.util.List<samplemodule.proxies.SubEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<samplemodule.proxies.SubEntity> result = new java.util.ArrayList<samplemodule.proxies.SubEntity>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SampleModule.SubEntity" + xpathConstraint))
			result.add(samplemodule.proxies.SubEntity.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SubTestText
	 */
	public final java.lang.String getSubTestText()
	{
		return getSubTestText(getContext());
	}

	/**
	 * @param context
	 * @return value of SubTestText
	 */
	public final java.lang.String getSubTestText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubTestText.toString());
	}

	/**
	 * Set value of SubTestText
	 * @param subtesttext
	 */
	public final void setSubTestText(java.lang.String subtesttext)
	{
		setSubTestText(getContext(), subtesttext);
	}

	/**
	 * Set value of SubTestText
	 * @param context
	 * @param subtesttext
	 */
	public final void setSubTestText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subtesttext)
	{
		getMendixObject().setValue(context, MemberNames.SubTestText.toString(), subtesttext);
	}

	/**
	 * @return value of SubEntity_TestEntityAssocAccount
	 */
	public final samplemodule.proxies.TestEntityAssocAccount getSubEntity_TestEntityAssocAccount() throws com.mendix.core.CoreException
	{
		return getSubEntity_TestEntityAssocAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of SubEntity_TestEntityAssocAccount
	 */
	public final samplemodule.proxies.TestEntityAssocAccount getSubEntity_TestEntityAssocAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		samplemodule.proxies.TestEntityAssocAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SubEntity_TestEntityAssocAccount.toString());
		if (identifier != null)
			result = samplemodule.proxies.TestEntityAssocAccount.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SubEntity_TestEntityAssocAccount
	 * @param subentity_testentityassocaccount
	 */
	public final void setSubEntity_TestEntityAssocAccount(samplemodule.proxies.TestEntityAssocAccount subentity_testentityassocaccount)
	{
		setSubEntity_TestEntityAssocAccount(getContext(), subentity_testentityassocaccount);
	}

	/**
	 * Set value of SubEntity_TestEntityAssocAccount
	 * @param context
	 * @param subentity_testentityassocaccount
	 */
	public final void setSubEntity_TestEntityAssocAccount(com.mendix.systemwideinterfaces.core.IContext context, samplemodule.proxies.TestEntityAssocAccount subentity_testentityassocaccount)
	{
		if (subentity_testentityassocaccount == null)
			getMendixObject().setValue(context, MemberNames.SubEntity_TestEntityAssocAccount.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SubEntity_TestEntityAssocAccount.toString(), subentity_testentityassocaccount.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return subEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final samplemodule.proxies.SubEntity that = (samplemodule.proxies.SubEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SampleModule.SubEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
